-- QuoteVault Seed Data
-- Migration 004: Seed database with 100+ quotes across 5 categories

-- Motivation quotes (25 quotes)
INSERT INTO quotes (text, author, category) VALUES
('The only way to do great work is to love what you do.', 'Steve Jobs', 'motivation'),
('Believe you can and you''re halfway there.', 'Theodore Roosevelt', 'motivation'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'motivation'),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'motivation'),
('It does not matter how slowly you go as long as you do not stop.', 'Confucius', 'motivation'),
('Everything you''ve ever wanted is on the other side of fear.', 'George Addair', 'motivation'),
('Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.', 'Roy T. Bennett', 'motivation'),
('I learned that courage was not the absence of fear, but the triumph over it.', 'Nelson Mandela', 'motivation'),
('There is only one way to avoid criticism: do nothing, say nothing, and be nothing.', 'Aristotle', 'motivation'),
('Do what you can with all you have, wherever you are.', 'Theodore Roosevelt', 'motivation'),
('You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis', 'motivation'),
('The only impossible journey is the one you never begin.', 'Tony Robbins', 'motivation'),
('In the middle of difficulty lies opportunity.', 'Albert Einstein', 'motivation'),
('Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson', 'motivation'),
('Keep your face always toward the sunshine—and shadows will fall behind you.', 'Walt Whitman', 'motivation'),
('What lies behind us and what lies before us are tiny matters compared to what lies within us.', 'Ralph Waldo Emerson', 'motivation'),
('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt', 'motivation'),
('Act as if what you do makes a difference. It does.', 'William James', 'motivation'),
('Success usually comes to those who are too busy to be looking for it.', 'Henry David Thoreau', 'motivation'),
('Don''t be pushed around by the fears in your mind. Be led by the dreams in your heart.', 'Roy T. Bennett', 'motivation'),
('The harder you work for something, the greater you''ll feel when you achieve it.', 'Unknown', 'motivation'),
('Dream bigger. Do bigger.', 'Unknown', 'motivation'),
('Don''t stop when you''re tired. Stop when you''re done.', 'Unknown', 'motivation'),
('Wake up with determination. Go to bed with satisfaction.', 'Unknown', 'motivation'),
('Do something today that your future self will thank you for.', 'Unknown', 'motivation');

-- Love quotes (25 quotes)
INSERT INTO quotes (text, author, category) VALUES
('Love is composed of a single soul inhabiting two bodies.', 'Aristotle', 'love'),
('The best thing to hold onto in life is each other.', 'Audrey Hepburn', 'love'),
('Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day.', 'Unknown', 'love'),
('You know you''re in love when you can''t fall asleep because reality is finally better than your dreams.', 'Dr. Seuss', 'love'),
('Love is when the other person''s happiness is more important than your own.', 'H. Jackson Brown Jr.', 'love'),
('The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.', 'Victor Hugo', 'love'),
('To love and be loved is to feel the sun from both sides.', 'David Viscott', 'love'),
('Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.', 'Maya Angelou', 'love'),
('Where there is love there is life.', 'Mahatma Gandhi', 'love'),
('Love is friendship that has caught fire.', 'Ann Landers', 'love'),
('The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.', 'Helen Keller', 'love'),
('Love doesn''t make the world go round. Love is what makes the ride worthwhile.', 'Franklin P. Jones', 'love'),
('You are my today and all of my tomorrows.', 'Leo Christopher', 'love'),
('In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.', 'Maya Angelou', 'love'),
('Love is a friendship set to music.', 'Joseph Campbell', 'love'),
('The giving of love is an education in itself.', 'Eleanor Roosevelt', 'love'),
('Love is the only force capable of transforming an enemy into a friend.', 'Martin Luther King Jr.', 'love'),
('Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.', 'Lao Tzu', 'love'),
('Love is like the wind, you can''t see it but you can feel it.', 'Nicholas Sparks', 'love'),
('The best love is the kind that awakens the soul and makes us reach for more.', 'Nicholas Sparks', 'love'),
('Love is not something you find. Love is something that finds you.', 'Loretta Young', 'love'),
('To love is nothing. To be loved is something. But to love and be loved, that''s everything.', 'T. Tolis', 'love'),
('Love is the bridge between you and everything.', 'Rumi', 'love'),
('Love is an endless act of forgiveness.', 'Beyoncé', 'love'),
('The heart wants what it wants.', 'Woody Allen', 'love');

-- Success quotes (25 quotes)
INSERT INTO quotes (text, author, category) VALUES
('Success is not the key to happiness. Happiness is the key to success.', 'Albert Schweitzer', 'success'),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill', 'success'),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'success'),
('Don''t be afraid to give up the good to go for the great.', 'John D. Rockefeller', 'success'),
('I find that the harder I work, the more luck I seem to have.', 'Thomas Jefferson', 'success'),
('Success is not how high you have climbed, but how you make a positive difference to the world.', 'Roy T. Bennett', 'success'),
('Opportunities don''t happen. You create them.', 'Chris Grosser', 'success'),
('Success is liking yourself, liking what you do, and liking how you do it.', 'Maya Angelou', 'success'),
('Try not to become a man of success. Rather become a man of value.', 'Albert Einstein', 'success'),
('The secret of success is to do the common thing uncommonly well.', 'John D. Rockefeller Jr.', 'success'),
('I never dreamed about success, I worked for it.', 'Estée Lauder', 'success'),
('Success seems to be connected with action. Successful people keep moving.', 'Conrad Hilton', 'success'),
('The road to success and the road to failure are almost exactly the same.', 'Colin R. Davis', 'success'),
('Success is the sum of small efforts repeated day in and day out.', 'Robert Collier', 'success'),
('Don''t aim for success if you want it; just do what you love and believe in, and it will come naturally.', 'David Frost', 'success'),
('Success is not in what you have, but who you are.', 'Bo Bennett', 'success'),
('The only place where success comes before work is in the dictionary.', 'Vidal Sassoon', 'success'),
('Success is getting what you want, happiness is wanting what you get.', 'W. P. Kinsella', 'success'),
('Success is not measured by what you accomplish, but by the opposition you have encountered.', 'Orison Swett Marden', 'success'),
('The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.', 'Vince Lombardi', 'success'),
('Success is doing ordinary things extraordinarily well.', 'Jim Rohn', 'success'),
('Success doesn''t just find you. You have to go out and get it.', 'Unknown', 'success'),
('The successful warrior is the average man, with laser-like focus.', 'Bruce Lee', 'success'),
('Success is the progressive realization of a worthy goal or ideal.', 'Earl Nightingale', 'success'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston S. Churchill', 'success');

-- Wisdom quotes (25 quotes)
INSERT INTO quotes (text, author, category) VALUES
('The only true wisdom is in knowing you know nothing.', 'Socrates', 'wisdom'),
('The journey of a thousand miles begins with one step.', 'Lao Tzu', 'wisdom'),
('In the end, we will remember not the words of our enemies, but the silence of our friends.', 'Martin Luther King Jr.', 'wisdom'),
('The greatest glory in living lies not in never falling, but in rising every time we fall.', 'Nelson Mandela', 'wisdom'),
('The mind is everything. What you think you become.', 'Buddha', 'wisdom'),
('Life is what happens when you''re busy making other plans.', 'John Lennon', 'wisdom'),
('The unexamined life is not worth living.', 'Socrates', 'wisdom'),
('Turn your wounds into wisdom.', 'Oprah Winfrey', 'wisdom'),
('Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.', 'Bill Keane', 'wisdom'),
('It is during our darkest moments that we must focus to see the light.', 'Aristotle', 'wisdom'),
('Whoever is happy will make others happy too.', 'Anne Frank', 'wisdom'),
('Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.', 'Buddha', 'wisdom'),
('The only way to make sense out of change is to plunge into it, move with it, and join the dance.', 'Alan Watts', 'wisdom'),
('We cannot solve problems with the kind of thinking we employed when we came up with them.', 'Albert Einstein', 'wisdom'),
('Learn as if you will live forever, live like you will die tomorrow.', 'Mahatma Gandhi', 'wisdom'),
('When you change your thoughts, remember to also change your world.', 'Norman Vincent Peale', 'wisdom'),
('It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.', 'Maurice Switzer', 'wisdom'),
('The fool doth think he is wise, but the wise man knows himself to be a fool.', 'William Shakespeare', 'wisdom'),
('Knowing yourself is the beginning of all wisdom.', 'Aristotle', 'wisdom'),
('The only thing necessary for the triumph of evil is for good men to do nothing.', 'Edmund Burke', 'wisdom'),
('Be kind, for everyone you meet is fighting a hard battle.', 'Plato', 'wisdom'),
('The best time to plant a tree was 20 years ago. The second best time is now.', 'Chinese Proverb', 'wisdom'),
('A wise man can learn more from a foolish question than a fool can learn from a wise answer.', 'Bruce Lee', 'wisdom'),
('The measure of intelligence is the ability to change.', 'Albert Einstein', 'wisdom'),
('We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'Aristotle', 'wisdom');

-- Humor quotes (25 quotes)
INSERT INTO quotes (text, author, category) VALUES
('I''m not superstitious, but I am a little stitious.', 'Michael Scott', 'humor'),
('The road to success is dotted with many tempting parking spaces.', 'Will Rogers', 'humor'),
('I always wanted to be somebody, but now I realize I should have been more specific.', 'Lily Tomlin', 'humor'),
('Behind every great man is a woman rolling her eyes.', 'Jim Carrey', 'humor'),
('The difference between stupidity and genius is that genius has its limits.', 'Albert Einstein', 'humor'),
('If you think you are too small to make a difference, try sleeping with a mosquito.', 'Dalai Lama', 'humor'),
('A day without sunshine is like, you know, night.', 'Steve Martin', 'humor'),
('I''m writing a book. I''ve got the page numbers done.', 'Steven Wright', 'humor'),
('The elevator to success is out of order. You''ll have to use the stairs, one step at a time.', 'Joe Girard', 'humor'),
('People say nothing is impossible, but I do nothing every day.', 'A.A. Milne', 'humor'),
('The best way to teach your kids about taxes is by eating 30% of their ice cream.', 'Bill Murray', 'humor'),
('I''m not lazy, I''m just on energy-saving mode.', 'Unknown', 'humor'),
('Common sense is like deodorant. The people who need it most never use it.', 'Unknown', 'humor'),
('I don''t need a hair stylist, my pillow gives me a new hairstyle every morning.', 'Unknown', 'humor'),
('I''m not arguing, I''m just explaining why I''m right.', 'Unknown', 'humor'),
('Life is short. Smile while you still have teeth.', 'Unknown', 'humor'),
('I''m on a seafood diet. I see food and I eat it.', 'Unknown', 'humor'),
('The only mystery in life is why the kamikaze pilots wore helmets.', 'Al McGuire', 'humor'),
('If at first you don''t succeed, then skydiving definitely isn''t for you.', 'Steven Wright', 'humor'),
('Age is of no importance unless you''re a cheese.', 'Billie Burke', 'humor'),
('The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.', 'Terry Pratchett', 'humor'),
('I used to think I was indecisive, but now I''m not so sure.', 'Unknown', 'humor'),
('The early bird gets the worm, but the second mouse gets the cheese.', 'Unknown', 'humor'),
('I''m not great at the advice. Can I interest you in a sarcastic comment?', 'Chandler Bing', 'humor'),
('Wine is constant proof that God loves us and loves to see us happy.', 'Benjamin Franklin', 'humor');

-- Additional quotes to reach 100+ (5 more per category = 25 total)
INSERT INTO quotes (text, author, category) VALUES
('Start where you are. Use what you have. Do what you can.', 'Arthur Ashe', 'motivation'),
('The only person you are destined to become is the person you decide to be.', 'Ralph Waldo Emerson', 'motivation'),
('Go confidently in the direction of your dreams. Live the life you have imagined.', 'Henry David Thoreau', 'motivation'),
('When you have a dream, you''ve got to grab it and never let go.', 'Carol Burnett', 'motivation'),
('Nothing is impossible. The word itself says I''m possible!', 'Audrey Hepburn', 'motivation'),
('Love all, trust a few, do wrong to none.', 'William Shakespeare', 'love'),
('Love cures people - both the ones who give it and the ones who receive it.', 'Karl Menninger', 'love'),
('The greatest thing you''ll ever learn is just to love and be loved in return.', 'Eden Ahbez', 'love'),
('Love is a canvas furnished by nature and embroidered by imagination.', 'Voltaire', 'love'),
('There is always some madness in love. But there is also always some reason in madness.', 'Friedrich Nietzsche', 'love'),
('The only way to achieve the impossible is to believe it is possible.', 'Charles Kingsleigh', 'success'),
('Success is not about being the best. It''s about always getting better.', 'Behance', 'success'),
('Fall seven times and stand up eight.', 'Japanese Proverb', 'success'),
('Success is peace of mind, which is a direct result of self-satisfaction.', 'John Wooden', 'success'),
('The secret to success is to know something nobody else knows.', 'Aristotle Onassis', 'success'),
('The wise man does at once what the fool does finally.', 'Niccolo Machiavelli', 'wisdom'),
('The invariable mark of wisdom is to see the miraculous in the common.', 'Ralph Waldo Emerson', 'wisdom'),
('Wisdom is not a product of schooling but of the lifelong attempt to acquire it.', 'Albert Einstein', 'wisdom'),
('The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.', 'Isaac Asimov', 'wisdom'),
('By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.', 'Confucius', 'wisdom'),
('I intend to live forever. So far, so good.', 'Steven Wright', 'humor'),
('My fake plants died because I did not pretend to water them.', 'Mitch Hedberg', 'humor'),
('I''m sick of following my dreams. I''m just going to ask them where they''re going and hook up with them later.', 'Mitch Hedberg', 'humor'),
('Clothes make the man. Naked people have little or no influence on society.', 'Mark Twain', 'humor'),
('Before you marry a person, you should first make them use a computer with slow Internet to see who they really are.', 'Will Ferrell', 'humor');
